#include "spac/codegen/impl_cpp.hpp"
#include "spac/registry.hpp"
#include "spac/layout.hpp"

#include <fstream>
#include <stdexcept>

namespace SPAC {
namespace codegen {

namespace {

int routing_key_bits() {
    auto& reg = internal::Registry::get();
    if (!reg.routing_key_set) {
        throw std::runtime_error(
            "compile_lib: SPAC::set_routing_key was never called.");
    }
    return reg.routing_src.bits;
}

// Returns 0 when the user did not call set_app_id; the emitter then leaves
// net-blocks at its default 16-bit app_id so user-space port numbers
// (e.g. 8080/8081) survive on the wire.
int app_id_bits() {
    auto& reg = internal::Registry::get();
    return reg.app_id_set ? reg.app_id.bits : 0;
}

const char* inorder_strategy() {
    // The DSL emits a stack with reliability disabled; drop_out_of_order /
    // hold_forever both depend on sequencing semantics the tiny stack does
    // not provide. flow_id is informational today.
    return "no_inorder";
}

}  // namespace

void write_netblocks_impl_cpp(const std::string& path) {
    const int routing_bits = routing_key_bits();
    const int app_bits     = app_id_bits();

    std::ofstream os(path);
    if (!os) {
        throw std::runtime_error("Cannot open impl.cpp output: " + path);
    }

    os << "// Auto-generated by SPAC DSL. Do not edit by hand.\n";
    os << "#include \"core/impls.h\"\n\n";
    os << "using namespace net_blocks;\n\n";
    os << "int main(int argc, char* argv[]) {\n";
    os << "    if (argc < 3) {\n";
    os << "        std::cerr << \"Usage: \" << argv[0]\n";
    os << "                  << \" <gen header file> <gen src file>\\n\";\n";
    os << "        return -1;\n";
    os << "    }\n\n";

    os << "    interface_module::instance.init_module();\n\n";

    os << "    identifier_module::instance.configFlowIdentifier(\n";
    os << "        identifier_module::flow_identifier_t::src_dst_identifier);\n";
    os << "    identifier_module::instance.set_host_range(0, 1ULL << "
       << routing_bits << ");\n";
    if (app_bits > 0) {
        os << "    identifier_module::instance.set_app_range(0, 1ULL << "
           << app_bits << ");\n";
    }
    os << "\n";

    os << "    reliable_module::instance.configDisableReliability();\n";
    os << "    checksum_module::instance.configDisableChecksum();\n";
    os << "    routing_module::instance.configDisableRouting();\n\n";

    os << "    inorder_module::instance.configInorderStrategy(\n";
    os << "        inorder_module::" << inorder_strategy() << ");\n\n";

    os << "    signaling_module::instance.configEnableSignaling();\n\n";

    os << "    payload_module::instance.init_module();\n";
    os << "    signaling_module::instance.init_module();\n";
    os << "    inorder_module::instance.init_module();\n";
    os << "    reliable_module::instance.init_module();\n";
    os << "    identifier_module::instance.init_module();\n";
    os << "    signaling_module_after::instance.init_module();\n";
    os << "    routing_module::instance.init_module();\n";
    os << "    checksum_module::instance.init_module();\n";
    os << "    network_module::instance.init_module();\n\n";

    os << "    net_packet.fix_layout();\n";
    os << "    net_packet.print_layout(std::cerr);\n\n";
    os << "    run_nb_pipeline(argv[1], argv[2]);\n";
    os << "    return 0;\n";
    os << "}\n";
}

}  // namespace codegen
}  // namespace SPAC
