#include "spac/codegen/netblocks.hpp"

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#ifndef SPAC_NETBLOCKS_ROOT
#  error "SPAC_NETBLOCKS_ROOT must be defined at compile time"
#endif

namespace SPAC {
namespace codegen {

namespace fs = std::filesystem;

namespace {

const fs::path nb_root = SPAC_NETBLOCKS_ROOT;

void run_or_throw(const std::string& cmd) {
    int rc = std::system(cmd.c_str());
    if (rc != 0) {
        throw std::runtime_error("Command failed (rc=" + std::to_string(rc)
                                 + "): " + cmd);
    }
}

void copy_runtime_files(const fs::path& dst_nb_root) {
    static const std::vector<std::string> files = {
        "nb_data_queue.h",
        "nb_runtime.h", "nb_runtime.c",
        "nb_timer.h",   "nb_timer.c",
        "nb_ipc_transport.c",
    };
    for (const auto& f : files) {
        const fs::path src = nb_root / "runtime" / f;
        const fs::path dst = dst_nb_root / f;
        if (!fs::exists(src)) {
            throw std::runtime_error("Missing runtime file: " + src.string());
        }
        fs::copy_file(src, dst, fs::copy_options::overwrite_existing);
    }
}

void write_makefile_frag(const fs::path& dst_nb_root) {
    std::ofstream os(dst_nb_root / "Makefile.frag");
    os <<
        "# Auto-generated by SPAC DSL. include this from your app Makefile:\n"
        "#     include path/to/netblocks/Makefile.frag\n"
        "#     myapp: $(NB_OBJS) myapp.o\n"
        "#         $(CC) $(NB_OBJS) myapp.o -o myapp\n"
        "\n"
        "NB_DIR    := $(dir $(lastword $(MAKEFILE_LIST)))\n"
        "NB_CFLAGS := -O3 -fno-strict-aliasing -I$(NB_DIR)\n"
        "NB_CSRCS  := $(NB_DIR)nb_proto.c \\\n"
        "             $(NB_DIR)nb_runtime.c \\\n"
        "             $(NB_DIR)nb_timer.c \\\n"
        "             $(NB_DIR)nb_ipc_transport.c\n"
        "NB_OBJS   := $(NB_CSRCS:.c=.o)\n"
        "\n"
        "%.o: %.c\n"
        "\t$(CC) $(NB_CFLAGS) -c $< -o $@\n"
        "\n"
        ".PHONY: nb_clean\n"
        "nb_clean:\n"
        "\trm -f $(NB_OBJS)\n";
}

}  // namespace

NetblocksArtifacts build_netblocks_stack(const std::string& impl_cpp_path,
                                         const std::string& dst_nb_root_str) {
    const fs::path dst_nb_root = dst_nb_root_str;
    fs::create_directories(dst_nb_root);

    const fs::path scratch = fs::path(impl_cpp_path).parent_path();
    const fs::path impl_bin    = scratch / "spac_impl";
    const fs::path proto_txt   = scratch / "proto.txt";
    const fs::path gen_headers = scratch / "gen_headers.h";
    const fs::path nb_proto_c  = scratch / "nb_proto.c";

    {
        std::ostringstream cmd;
        cmd << "g++ -std=c++11 -O2 -rdynamic"
            << " -I" << (nb_root / "include").string()
            << " -I" << (nb_root / "buildit/include").string()
            << " -L" << (nb_root / "build").string()
            << " -L" << (nb_root / "buildit/build").string()
            << " -o " << impl_bin.string()
            << " " << impl_cpp_path
            << " -lnet_blocks -lbuildit"
            << " 2>&1";
        run_or_throw(cmd.str());
    }

    {
        std::ostringstream cmd;
        cmd << impl_bin.string()
            << " " << gen_headers.string()
            << " " << nb_proto_c.string()
            << " 2> " << proto_txt.string();
        run_or_throw(cmd.str());
    }

    fs::copy_file(gen_headers, dst_nb_root / "gen_headers.h",
                  fs::copy_options::overwrite_existing);
    fs::copy_file(nb_proto_c, dst_nb_root / "nb_proto.c",
                  fs::copy_options::overwrite_existing);
    copy_runtime_files(dst_nb_root);

    write_makefile_frag(dst_nb_root);

    NetblocksArtifacts art;
    art.proto_txt_path   = proto_txt.string();
    art.gen_headers_path = (dst_nb_root / "gen_headers.h").string();
    art.nb_proto_c_path  = (dst_nb_root / "nb_proto.c").string();
    return art;
}

}  // namespace codegen
}  // namespace SPAC
