#include "spac/codegen/packet_hpp.hpp"
#include "spac/registry.hpp"

#include <fstream>
#include <regex>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>

namespace SPAC {
namespace codegen {

namespace {

struct ProtoField {
    int width  = 0;
    int offset = 0;
};

int read_packet_headroom(const std::string& gen_headers_path) {
    std::ifstream is(gen_headers_path);
    if (!is) {
        throw std::runtime_error("Cannot open " + gen_headers_path);
    }
    static const std::regex pat(
        R"(nb__packet_headroom\s*=\s*([0-9]+))");
    std::string line;
    while (std::getline(is, line)) {
        std::smatch m;
        if (std::regex_search(line, m, pat)) {
            return std::stoi(m[1].str());
        }
    }
    throw std::runtime_error(
        "nb__packet_headroom not found in " + gen_headers_path);
}

std::unordered_map<std::string, ProtoField> read_proto_layout(
    const std::string& proto_txt_path) {
    std::ifstream is(proto_txt_path);
    if (!is) {
        throw std::runtime_error("Cannot open " + proto_txt_path);
    }
    std::unordered_map<std::string, ProtoField> out;
    static const std::regex pat(
        R"(^\s*([A-Za-z_][A-Za-z0-9_]*)\s*:([0-9]+)\(([0-9]+)\))");
    std::string line;
    while (std::getline(is, line)) {
        std::smatch m;
        if (std::regex_search(line, m, pat)) {
            ProtoField f;
            f.width  = std::stoi(m[2].str());
            f.offset = std::stoi(m[3].str());
            out[m[1].str()] = f;
        }
    }
    return out;
}

const ProtoField& require(
    const std::unordered_map<std::string, ProtoField>& fields,
    const std::string& name,
    const std::string& proto_txt_path) {
    auto it = fields.find(name);
    if (it == fields.end()) {
        throw std::runtime_error(
            "Field \"" + name + "\" not found in " + proto_txt_path);
    }
    return it->second;
}

}  // namespace

void write_packet_hpp(const std::string& proto_txt_path,
                      const std::string& gen_headers_path,
                      const std::string& out_packet_hpp_path) {
    const int headroom_bytes = read_packet_headroom(gen_headers_path);
    const int headroom_bits  = headroom_bytes * 8;

    auto fields = read_proto_layout(proto_txt_path);

    const ProtoField src_f     = require(fields, "src_host_id", proto_txt_path);
    const ProtoField dst_f     = require(fields, "dst_host_id", proto_txt_path);
    const ProtoField pkt_len_f = require(fields, "total_len",   proto_txt_path);

    const int src_w   = src_f.width;
    const int dst_w   = dst_f.width;
    const int len_w   = pkt_len_f.width;
    const int src_off = src_f.offset     - headroom_bits;
    const int dst_off = dst_f.offset     - headroom_bits;
    const int len_off = pkt_len_f.offset - headroom_bits;

    std::ofstream os(out_packet_hpp_path);
    if (!os) {
        throw std::runtime_error("Cannot open " + out_packet_hpp_path);
    }

    os << "#pragma once\n";
    os << "// Auto-generated by SPAC DSL. Do not edit by hand.\n";
    os << "#include <ap_int.h>\n\n";

    os << "namespace spac_packet {\n\n";
    os << "constexpr int SRC_WIDTH     = " << src_w << ";\n";
    os << "constexpr int DST_WIDTH     = " << dst_w << ";\n";
    os << "constexpr int PKT_LEN_WIDTH = " << len_w << ";\n\n";

    os << "static_assert(SRC_WIDTH == DST_WIDTH,\n";
    os << "    \"Hash engine indexes the forwarding table by a single \"\n";
    os << "    \"address width.\");\n\n";

    os << "constexpr int SRC_OFFSET     = " << src_off << ";\n";
    os << "constexpr int DST_OFFSET     = " << dst_off << ";\n";
    os << "constexpr int PKT_LEN_OFFSET = " << len_off << ";\n\n";

    os <<
        "template <int Width, int Lo>\n"
        "inline ap_uint<Width> get_field(const ap_uint<512>& word) {\n"
        "#pragma HLS INLINE\n"
        "    return word.range(Lo + Width - 1, Lo);\n"
        "}\n\n"
        "template <int Width, int Lo>\n"
        "inline void set_field(ap_uint<512>& word, ap_uint<Width> v) {\n"
        "#pragma HLS INLINE\n"
        "    word.range(Lo + Width - 1, Lo) = v;\n"
        "}\n\n";

    os << "inline ap_uint<SRC_WIDTH>     get_src    (const ap_uint<512>& w) "
       << "{ return get_field<SRC_WIDTH,     SRC_OFFSET>    (w); }\n";
    os << "inline ap_uint<DST_WIDTH>     get_dst    (const ap_uint<512>& w) "
       << "{ return get_field<DST_WIDTH,     DST_OFFSET>    (w); }\n";
    os << "inline ap_uint<PKT_LEN_WIDTH> get_pkt_len(const ap_uint<512>& w) "
       << "{ return get_field<PKT_LEN_WIDTH, PKT_LEN_OFFSET>(w); }\n\n";

    os << "inline void set_src    (ap_uint<512>& w, ap_uint<SRC_WIDTH>     v) "
       << "{ set_field<SRC_WIDTH,     SRC_OFFSET>    (w, v); }\n";
    os << "inline void set_dst    (ap_uint<512>& w, ap_uint<DST_WIDTH>     v) "
       << "{ set_field<DST_WIDTH,     DST_OFFSET>    (w, v); }\n";
    os << "inline void set_pkt_len(ap_uint<512>& w, ap_uint<PKT_LEN_WIDTH> v) "
       << "{ set_field<PKT_LEN_WIDTH, PKT_LEN_OFFSET>(w, v); }\n\n";

    os << "}  // namespace spac_packet\n\n";
    os << "constexpr int ADDR_LENGTH         = spac_packet::SRC_WIDTH;\n";
    os << "constexpr int PACKET_TOTAL_LENGTH = spac_packet::PKT_LEN_WIDTH;\n\n";
    os << "using spac_packet::get_src;\n";
    os << "using spac_packet::get_dst;\n";
    os << "using spac_packet::get_pkt_len;\n";
    os << "using spac_packet::set_src;\n";
    os << "using spac_packet::set_dst;\n";
    os << "using spac_packet::set_pkt_len;\n";
}

}  // namespace codegen
}  // namespace SPAC
